# Hexo 配置
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 站点
title: 七瀬丸のブログ
subtitle: 'あいうえお'
description: '◢₄₆此时,一位DD从坂道上经过'
keywords:
author: 七瀬丸
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## 在此处设置您的网站网址。例如，如果您使用 GitHub Page，则将 url 设置为 'https://username.github.io/project'
url: https://matthew.olddoge.cn
permalink: :year/:month/:hash/ #:year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 写作
new_post_name: :year/:month/:title.md # 新帖子的文件名 支持子文件夹
default_layout: post
titlecase: false # 将 title 转换为 titlecase
external_link:
  enable: true # 在新标签页中打开外部链接
  field: site # 适用于全站
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false  # 生成文章的时候同时生成对应的文件夹
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# 首页设置
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# 扩展
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: oranges

# 图片懒加载
# 需要先安装插件 npm install hexo-lazyload-image --save
lazyload:
  enable: true
  onlypost: false # optional
  loadingImg: # optional eg ./images/loading.gif
  isSPA: false # optional

# 全文搜索
# 需先安装 npm install hexo-generator-search --save
search:
  path: search.xml
  field: post
  content: true

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
# 部署多个 deploy
deploy:
  - type: git
    repo:
      alicloud: ssh://root@120.27.133.113:9222/mnt/gitrepo/MatthewBlog  # 自己的服务器
      gitee: https://gitee.com/olddoge/matthew  # 无page服务，纯备份
      github: https://github.com/olddoge/olddoge.github.io  # 国内无法访问
      olddoge: https://git.olddoge.cn/matthew/blog.git # 我的阿里云服务器的 codefever
    branch: master
  # Rsync 部署到云服务器
  # 需安装 npm install hexo-deployer-rsync --save
